### ISSUE TITLE
Building hwloc-2.0.1 with intel 2018 update 3 compiler.

### ISSUE THREAD

**Issue by spikebike** [open-mpi/hwloc#318]
My goal is a openmpi-3.1.1 build on ubuntu-18.04 with hwloc-2.0.1.

I've already managed to recompile libevent-2.1.8 and pmix-2.1.2.

I set CC=icc CXX=icpc F77=ifort FC=ifort then:
```
/share/apps/src/hwloc-2.0.1$ ./configure --prefix=/share/apps/hwloc-2.0.1/intel-2018 --enable-netloc
```
When I tried to compile:
```
/share/apps/src/hwloc-2.0.1$ make
Making all in include
make[1]: Entering directory '/share/apps/src/hwloc-2.0.1/include'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/share/apps/src/hwloc-2.0.1/include'
Making all in hwloc
make[1]: Entering directory '/share/apps/src/hwloc-2.0.1/hwloc'
  CC       distances.lo
In file included from /usr/include/math.h(325),
                 from /share/apps/intel-2018/compilers_and_libraries_2018.3.222/linux/compiler/include/math.h(173),
                 from distances.c(15):
/usr/include/bits/mathcalls.h(162): error: expected a type specifier
  __MATHCALLX (fabs,, (_Mdouble_ __x), (__const__));
  ^

distances.c(692): warning #266: function "fabsf" declared implicitly
    if (accuracy != 0.0f && fabsf((float)a-(float)b) < (float)a * accuracy)
                            ^

compilation aborted for distances.c (code 2)
Makefile:886: recipe for target 'distances.lo' failed
make[1]: *** [distances.lo] Error 1
make[1]: Leaving directory '/share/apps/src/hwloc-2.0.1/hwloc'
Makefile:629: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by bgoglin** [comment]
Hello
Did this problem appear recently after updating ICC? I can't reproduce with Intel "icc (ICC) 18.0.0 20170811" on Centos7, and I suspect we would have gotten many bug reports earlier since many people build MPIs with ICC. fabsf() should be defined thanks to distances.c doing #include <math.h>
Brice

**Comment by xxiaowenzip** [comment]
Hi,
I met the same problem when I tried to configure and build the openmpi 1.10.2 on Ubuntu 18.04 with Intel 2013. Have you solve the problem yet?

**Comment by bgoglin** [comment]
@xxiaowenzip We don't know. I'd vote for a problem with compiler headers but it strange because these things have been working fine for years for many people using the same compilers. Does another compiler fail to use /usr/include/bits/mathcalls.h on that same machine?

**Comment by bgoglin** [comment]
Some people say that this error occurs when fabsf (or fabs, not sure which one) is already defined before mathcalls.h gets included. hwloc defines its own fabsf() in include/private/misc.h when it fails to find it in system headers/libs.

Try disabling that part of include/private/misc.h to see if it helps. If so, look in config.log to find out why fabsf() wasn't detected at configure (or post config.log here). include/private/autogen/config.h should have HAVE_DECL_FABSF not set to 1 if configure failed to find it.

**Comment by bgoglin** [comment]
@spikebike @xxiaowenzip If you still have this issue, you may want to try this patch (assuming strange headers/compiler cause our configure detection of fabsf to misbehave).
https://github.com/bgoglin/hwloc/commit/1951097ff5928315bf0f90687ee9e25dbffcb2ab
Tarball available at https://ci.inria.fr/hwloc/job/zbgoglin-basic/lastSuccessfulBuild/artifact/hwloc-fabsf-20180928.1108.git1951097.tar.bz2 (until it disappears in the backlog).

**Comment by bgoglin** [comment]
I am closing this issue since I didn't get a reply. If anybody has the same issue, please try this patch (same as above):
```
--- a/config/hwloc.m4
+++ b/config/hwloc.m4
@@ -447,7 +447,8 @@ EOF])
                     AC_DEFINE([HAVE_LIBKSTAT], 1, [Define to 1 if we have -lkstat])])
     ])
 
-    AC_CHECK_DECLS([fabsf], [
+    _HWLOC_CHECK_DECL([fabsf], [
+      AC_DEFINE([HWLOC_HAVE_DECL_FABSF], [1], [Define to 1 if function `fabsf' is declared by system headers])
       AC_CHECK_LIB([m], [fabsf],
                    [need_libm=yes])
     ], [], [[#include <math.h>]])
--- a/include/private/misc.h
+++ b/include/private/misc.h
@@ -513,7 +513,7 @@ hwloc__obj_type_is_icache(hwloc_obj_type_t type)
 #define hwloc_localeswitch_fini()
 #endif /* HAVE_USELOCALE */
 
-#if !HAVE_DECL_FABSF
+#ifndef HWLOC_HAVE_DECL_FABSF
 #define fabsf(f) fabs((double)(f))
 #endif
 
```
